/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as JiraVsPlaneRouteImport } from './routes/jira-vs-plane'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ExpertsLovableRouteImport } from './routes/experts/lovable'
import { Route as ExpertsOutsystemsRouteImport } from './routes/experts/outsystems'
import { Route as PartnersPlaneRouteImport } from './routes/partners/plane'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesDevelopmentRouteImport } from './routes/services/development'
import { Route as ServicesImplementationRouteImport } from './routes/services/implementation'
import { Route as ServicesManagedRouteImport } from './routes/services/managed'
import { Route as ServicesMigrationRouteImport } from './routes/services/migration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const JiraVsPlaneRoute = JiraVsPlaneRouteImport.update({
  id: '/jira-vs-plane',
  path: '/jira-vs-plane',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsLovableRoute = ExpertsLovableRouteImport.update({
  id: '/experts/lovable',
  path: '/experts/lovable',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsOutsystemsRoute = ExpertsOutsystemsRouteImport.update({
  id: '/experts/outsystems',
  path: '/experts/outsystems',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersPlaneRoute = PartnersPlaneRouteImport.update({
  id: '/partners/plane',
  path: '/partners/plane',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDevelopmentRoute = ServicesDevelopmentRouteImport.update({
  id: '/services/development',
  path: '/services/development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesImplementationRoute = ServicesImplementationRouteImport.update({
  id: '/services/implementation',
  path: '/services/implementation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesManagedRoute = ServicesManagedRouteImport.update({
  id: '/services/managed',
  path: '/services/managed',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMigrationRoute = ServicesMigrationRouteImport.update({
  id: '/services/migration',
  path: '/services/migration',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/enterprise': typeof EnterpriseRoute
  '/jira-vs-plane': typeof JiraVsPlaneRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/experts/lovable': typeof ExpertsLovableRoute
  '/experts/outsystems': typeof ExpertsOutsystemsRoute
  '/partners/plane': typeof PartnersPlaneRoute
  '/services/development': typeof ServicesDevelopmentRoute
  '/services/implementation': typeof ServicesImplementationRoute
  '/services/managed': typeof ServicesManagedRoute
  '/services/migration': typeof ServicesMigrationRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/enterprise': typeof EnterpriseRoute
  '/jira-vs-plane': typeof JiraVsPlaneRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/experts/lovable': typeof ExpertsLovableRoute
  '/experts/outsystems': typeof ExpertsOutsystemsRoute
  '/partners/plane': typeof PartnersPlaneRoute
  '/services/development': typeof ServicesDevelopmentRoute
  '/services/implementation': typeof ServicesImplementationRoute
  '/services/managed': typeof ServicesManagedRoute
  '/services/migration': typeof ServicesMigrationRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/enterprise': typeof EnterpriseRoute
  '/jira-vs-plane': typeof JiraVsPlaneRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/experts/lovable': typeof ExpertsLovableRoute
  '/experts/outsystems': typeof ExpertsOutsystemsRoute
  '/partners/plane': typeof PartnersPlaneRoute
  '/services/development': typeof ServicesDevelopmentRoute
  '/services/implementation': typeof ServicesImplementationRoute
  '/services/managed': typeof ServicesManagedRoute
  '/services/migration': typeof ServicesMigrationRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/enterprise'
    | '/jira-vs-plane'
    | '/privacy'
    | '/solutions'
    | '/terms'
    | '/blog/$slug'
    | '/experts/lovable'
    | '/experts/outsystems'
    | '/partners/plane'
    | '/services/development'
    | '/services/implementation'
    | '/services/managed'
    | '/services/migration'
    | '/blog/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/enterprise'
    | '/jira-vs-plane'
    | '/privacy'
    | '/solutions'
    | '/terms'
    | '/blog/$slug'
    | '/experts/lovable'
    | '/experts/outsystems'
    | '/partners/plane'
    | '/services/development'
    | '/services/implementation'
    | '/services/managed'
    | '/services/migration'
    | '/blog'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/cookies'
    | '/enterprise'
    | '/jira-vs-plane'
    | '/privacy'
    | '/solutions'
    | '/terms'
    | '/blog/$slug'
    | '/experts/lovable'
    | '/experts/outsystems'
    | '/partners/plane'
    | '/services/development'
    | '/services/implementation'
    | '/services/managed'
    | '/services/migration'
    | '/blog/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  EnterpriseRoute: typeof EnterpriseRoute
  JiraVsPlaneRoute: typeof JiraVsPlaneRoute
  PrivacyRoute: typeof PrivacyRoute
  SolutionsRoute: typeof SolutionsRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ExpertsLovableRoute: typeof ExpertsLovableRoute
  ExpertsOutsystemsRoute: typeof ExpertsOutsystemsRoute
  PartnersPlaneRoute: typeof PartnersPlaneRoute
  ServicesDevelopmentRoute: typeof ServicesDevelopmentRoute
  ServicesImplementationRoute: typeof ServicesImplementationRoute
  ServicesManagedRoute: typeof ServicesManagedRoute
  ServicesMigrationRoute: typeof ServicesMigrationRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jira-vs-plane': {
      id: '/jira-vs-plane'
      path: '/jira-vs-plane'
      fullPath: '/jira-vs-plane'
      preLoaderRoute: typeof JiraVsPlaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts/lovable': {
      id: '/experts/lovable'
      path: '/experts/lovable'
      fullPath: '/experts/lovable'
      preLoaderRoute: typeof ExpertsLovableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts/outsystems': {
      id: '/experts/outsystems'
      path: '/experts/outsystems'
      fullPath: '/experts/outsystems'
      preLoaderRoute: typeof ExpertsOutsystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/plane': {
      id: '/partners/plane'
      path: '/partners/plane'
      fullPath: '/partners/plane'
      preLoaderRoute: typeof PartnersPlaneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/development': {
      id: '/services/development'
      path: '/services/development'
      fullPath: '/services/development'
      preLoaderRoute: typeof ServicesDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/implementation': {
      id: '/services/implementation'
      path: '/services/implementation'
      fullPath: '/services/implementation'
      preLoaderRoute: typeof ServicesImplementationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/managed': {
      id: '/services/managed'
      path: '/services/managed'
      fullPath: '/services/managed'
      preLoaderRoute: typeof ServicesManagedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/migration': {
      id: '/services/migration'
      path: '/services/migration'
      fullPath: '/services/migration'
      preLoaderRoute: typeof ServicesMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  EnterpriseRoute: EnterpriseRoute,
  JiraVsPlaneRoute: JiraVsPlaneRoute,
  PrivacyRoute: PrivacyRoute,
  SolutionsRoute: SolutionsRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ExpertsLovableRoute: ExpertsLovableRoute,
  ExpertsOutsystemsRoute: ExpertsOutsystemsRoute,
  PartnersPlaneRoute: PartnersPlaneRoute,
  ServicesDevelopmentRoute: ServicesDevelopmentRoute,
  ServicesImplementationRoute: ServicesImplementationRoute,
  ServicesManagedRoute: ServicesManagedRoute,
  ServicesMigrationRoute: ServicesMigrationRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
